all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
all_joints_names:
- finger1
- finger2
- finger3
- finger4
- paw
- wrist_joint
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
clahe: true
claheratio: 0.1
crop_sampling: hybrid
crop_size:
- 400
- 400
cropratio: 0.4
dataset: training-datasets\iteration-1\UnaugmentedDataSet_Center_mirrorSep2\Center_mirror_Daniil95shuffle2.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 1000
edge: false
emboss:
  alpha:
  - 0.0
  - 1.0
  embossratio: 0.1
  strength:
  - 0.5
  - 1.5
global_scale: 0.8
histeq: true
histeqratio: 0.1
init_weights: \\pn.vai.org\projects_primary\chu\Daniil Berezhnoi\Python programs\July Networks 2023\LeftHanded\Center_mirror-Daniil-2022-09-02\dlc-models\iteration-1\Center_mirrorSep2-trainset95shuffle2\snapshot-1
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
max_shift: 0.4
metadataset: training-datasets\iteration-1\UnaugmentedDataSet_Center_mirrorSep2\Documentation_data-Center_mirror_95shuffle2.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 6
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
pre_resize: []
project_path: \\pn.vai.org\projects_primary\chu\Daniil Berezhnoi\Python programs\July
  Networks 2023\LeftHanded\Center_mirror-Daniil-2022-09-02
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: false
sharpenratio: 0.3
